global using Microsoft.EntityFrameworkCore;
global using Talabat.Domain.Common;
global using Talabat.Domain.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Talabat.Infrastructure.Persistence.Data.Configurations.Base;
global using Talabat.Domain.Contracts;
global using Talabat.Infrastructure.Persistence.Data;
global using Talabat.Infrastructure.Persistence.Repositories;
global using Talabat.Domain.Contracts.Presistence;
